import React from 'react';
import { MoveUpRight } from "lucide-react";
import HeaderHome from "./header/HeaderHome";
import { useNavigate } from "react-router-dom";
import Cookies from "universal-cookie";
import { useEffect } from "react";

export default function Home() {
    const navigate = useNavigate();
    const cookies = new Cookies(null, { path: '/' });

    useEffect(() => {
        if (!cookies.get('uid') || !cookies.get('email'))
            navigate('/');
    }, []);

    return (
        <>
            <div className="w-[60%] h-full relative flex flex-col items-center justify-start">
                <div className="fixed w-full h-full inset-0 overflow-hidden z-10">
                    <div className='w-full h-full relative'>
                        <div className="absolute -top-36 -left-40 w-96 h-60 bg-emerald-800/80 rounded-full  mix-blend-multiply filter blur-3xl"></div>
                        <div className="absolute top-0 -right-40 w-96 h-96 bg-green-900/30 rounded-full mix-blend-multiply filter blur-3xl"></div>
                        {/* <div className="absolute -bottom-40 left-20 w-96 h-96 bg-teal-900/30 rounded-full mix-blend-multiply filter blur-3xl">THIHISHSIH</div> */}
                    </div>
                </div>
                <HeaderHome />

                
                <div className="w-full h-full flex items-center z-20 flex-col justify-start gap-2 relative mt-2">
                    <p className='w-full mt-10 mb-2 font-semibold text-2xl'>Welcome, <span className='text-green-400'>{cookies.get('name')}</span></p>
                    <div className="w-full h-full flex items-center justify-start gap-2 relative mt-2">
                        <div onClick={() => navigate(`/${cookies.get('uid')}/web-img-video`)} className="w-full cursor-pointer hover:border-white/40 hover:opacity-75 transition-all duration-300 hover:z-30 shadow-2xl relative rounded-lg border border-white/20 h-full flex items-center justify-start gap-2 backdrop-blur-sm bg-black/10">
                            <div className="w-full z-20 p-4 flex relative h-64 items-start justify-start gap-4 flex-col rounded-lg">
                                <p className="font-bold text-3xl max-w-[65%]">Generate mini video from <span className="text-green-400">web-searched images</span></p>
                                <p className="text-sm max-w-[70%] text-gray-300">Background images are trimmed and merged from the available free web-searched images</p>
                                <button className="absolute right-3 bottom-2 z-20 hover:scale-125 transition-all duration-300 hover:cursor-pointer"><MoveUpRight className="w-7 h-7" strokeWidth={3} /></button>
                            </div>
                        </div>

                        <div onClick={() => navigate(`/${cookies.get('uid')}/generate-video-from-stock`)} className="w-full cursor-pointer hover:border-white/40 hover:opacity-75 transition-all duration-300 hover:z-30 shadow-2xl relative rounded-lg border border-white/20 h-full flex items-center justify-start gap-2 backdrop-blur-sm bg-black/10">
                            <div className="w-full p-4 gap-4 relative h-64 flex items-start justify-start flex-col rounded-lg">
                                <p className="font-bold text-3xl max-w-[65%]">Generate mini video from <span className="text-green-400">stock videos</span></p>
                                <p className="text-sm max-w-[70%] text-gray-300">Background videos are trimmed and merged from the available free stock videos</p>
                                <button className="absolute right-3 bottom-2 z-20 hover:scale-125 transition-all duration-300 hover:cursor-pointer"><MoveUpRight className="w-7 h-7" strokeWidth={3} /></button>
                            </div>
                        </div> 
                    </div>

                    <div className="w-full h-full flex items-center justify-start gap-2 relative">
                        <div onClick={() => navigate(`/${cookies.get('uid')}/generate-video-from-ai`)} className="w-full cursor-pointer hover:border-white/40 hover:opacity-75 transition-all duration-300 hover:z-30 shadow-2xl relative rounded-lg border border-white/20 h-full flex items-center justify-start gap-2 backdrop-blur-sm bg-black/10">
                            <div className="w-full p-4 gap-4 relative h-64 flex items-start justify-start flex-col rounded-lg">
                                <p className="font-bold text-3xl max-w-[65%]">Generate mini video from <span className="text-green-400">AI-generated images</span></p>
                                <p className="text-sm max-w-[70%] text-gray-300">Background images are generated by AI based on the script and merge them to generate the final video</p>
                                <button className="absolute right-3 bottom-2 z-20 hover:scale-125 transition-all duration-300 hover:cursor-pointer"><MoveUpRight className="w-7 h-7" strokeWidth={3} /></button>
                            </div>
                        </div>

                        <div className="w-full cursor-pointer hover:border-white/40 hover:opacity-75 transition-all duration-300 hover:z-30 shadow-2xl relative rounded-lg border border-white/20 h-full flex items-center justify-start gap-2 backdrop-blur-sm bg-black/10">
                            <div className="w-full p-4 gap-4 relative h-64 flex items-start justify-start flex-col rounded-lg">
                                <p className="font-bold text-3xl max-w-[65%]">Generate mini video for <span className="text-green-400">marketing your product</span></p>
                                <p className="text-sm max-w-[70%] text-gray-300">Includes clicking a few pictures of your product which is to be shown in the generated video, script can be edited as per user's choice</p>
                                <button className="absolute right-3 bottom-2 z-20 hover:scale-125 transition-all duration-300 hover:cursor-pointer"><MoveUpRight className="w-7 h-7" strokeWidth={3} /></button>
                            </div>
                        </div>
                    </div>

                    <div className="w-full flex items-center justify-start gap-2 relative">
                        <div onClick={() => navigate(`/${cookies.get('uid')}/canvas`)} className="w-[50%] cursor-pointer hover:border-white/40 hover:opacity-75 transition-all duration-300 hover:z-30 shadow-2xl relative rounded-lg border border-white/20 h-full flex items-center justify-start gap-2 backdrop-blur-sm bg-black/10">
                            <div className="w-full relative p-4 h-64 gap-4 flex items-start justify-start flex-col rounded-lg">
                                <p className="font-bold text-3xl max-w-[65%]">Generate AI videos from <span className="text-green-400">your drawning</span></p>
                                <p className="text-sm max-w-[70%] text-gray-300">Convert your drawn images into the AI generated with the style you want</p>
                                <button className="absolute right-3 bottom-2 z-20 hover:scale-125 transition-all duration-300 hover:cursor-pointer"><MoveUpRight className="w-7 h-7" strokeWidth={3} /></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}